### ISSUE TITLE
Version in master and development branch should end in -SNAPSHOT

### ISSUE THREAD

**Issue by reckart** [lapps/org.lappsgrid.serialization#10]
Version in master and development branch should end in -SNAPSHOT.

**Comment by ksuderman** [comment]
No they shouldn't. At least not in our work flow :-)

We (I) follow a slightly modified Git Flow workflow. The master branch will always contain the latest release version with an unqualified version number;  basically master and the latest tagged version will (should) always be the same.  Development work is performed on feature branches and merged into develop as the features are completed. A release then consists of the following steps:

 - create a release branch from the develop branch
 - strip SNAPSHOT from the version
 - perform any last minute bug fixes, documentation updates, etc.
 - deploy all artifacts to Nexus from the release branch.
 - merge the release branch into master.
 - tag the master branch 
 - merge the master branch into the develop branch for the next cycle

If the develop branch does not have a SNAPSHOT version it simply means that no features have been merged into develop since the last release.

**Comment by reckart** [comment]
This is rather inconvenient if anybody would want to add this project to the CI system. The CI shouldn't accidentally build an alternative JAR for a release version and deploy it to a repo. Even with the feature branch approach, you could still do releases using the Maven Release plugin and ensure that the project adheres to Maven best practices.

**Comment by ksuderman** [comment]
Could you explain further?  What CI system are you using?  What is inconvenient? 

I haven't used the Maven Release plugin for some time, and it is unlikely I will go back to using it for various reasons (some technical and some religious). Although I may take a look at the jgitflow-maven-plugin at some point in the future.

I haven't configured Travis to deploy artifacts yet, but I use it in another project to test, build, and deploy and I haven't run into any problems.  

```yaml
# .travis.yml
branches:
	only:
	-master
	-develop
# Environment variables containing login credentials for GitHub and Nexus
env:
	global:
	- secure: <gibberish>
	...
script:
	- mvn clean test --settings settings.xml
after_success:
	- if [ "$TRAVIS_BRANCH" == "master"] ; then 
	    	mvn javadoc:jar source:jar deploy --settings settings.xml; 
		mvn site --settings settings.xml
  	   fi
```

 A typical release cycle (for v1.0.0 say) looks like:
```bash
$ release start 1.0.0
$ mvn versions:set -DnewVersion=1.0.0
$ release finish 1.0.0
```
Travis does the building and deploying and GitFlow does the branching, tagging, and merging.  The only thing missing is bumping the develop branch to the next SNAPSHOT version, and that is because after 1.0.0 does 1.0.1-SNAPSHOT, 1.1.0-SNAPSHOT, or 2.0.0-SNAPSHOT come next?  I like to make that decision at the start of the next development cycle and not at the end of the previous release cycle.
